### ISSUE TITLE
Create Source Maps

### ISSUE THREAD

**Issue by ChadKillingsworth** [Banno/polymer-webpack-loader#6]
The loader does some pretty drastic transformations on the HTML scripts. We need to add source map support.

The [vue loader](https://github.com/vuejs/vue-loader) does something similar so we should look at how it does it.

[Polymer-bundler](https://github.com/Polymer/polymer-bundler/blob/master/src/source-map.ts) has source map support for inline script tags in HTML files. That can also be used as a reference.

**Comment by eheikes** [comment]
(In case it's not obvious, [source-map](https://www.npmjs.com/package/source-map) is the go-to module for this.)
